version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peekaboo_symfony
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/app"
  
  db:
    image: postgres:14
    container_name: peekaboo_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5435:5435"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  front:
    build:
      context: ../peekabofront
      dockerfile: Dockerfile.front
    container_name: peekaboo_front
    ports:
      - "8010:8010"
    volumes:
      - ../peekabofront:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://app:80
    depends_on:
      - app
volumes:
  postgres_data:
