version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peekaboo_symfony
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:your_password@db:5432/app"
  
  db:
    image: postgres:14
    container_name: peekaboo_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
